PetroReclutamiento/urls.py
from django.conf.urls import url, include, handler403, handler404, handler500
from django.contrib import admin
# STATICFILES
from django.conf import settings
from django.conf.urls.static import static
from usuarios import views as users_views
from maestros import views as maestros_views
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^password_change/$', auth_views.password_change, name='password_change'),
    url(r'^password_change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^$', RedirectView.as_view(pattern_name='login', permanent=False)),
    url(r'^login/', users_views.login_view, name='login'),
    url(r'^logout/', users_views.logout_view),
    url(r'^admin/', admin.site.urls),
    url(r'^convocatorias/', include('convocatorias.urls')),
    url(r'^publico/', include('publico.urls')),
    url(r'^personas/', include('usuarios.urls')),
    url(r'^atenciones/', include('atenciones.urls')),
    url(r'^educativo/', include('educativo.urls')),
    url(r'^laboral/', include('laboral.urls')),
    url(r'^cursos/', include('cursos.urls')),
    url(r'^api/maestros/', include('maestros.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
    # url(r'^.*$', RedirectView.as_view(pattern_name='login', permanent=False))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler403 = maestros_views.handler403
handler404 = maestros_views.handler404
handler500 = maestros_views.handler500

cursos/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	# PERSONA
	url(r'^persona/(?P<uuid>[^/]+)/add/$', views.add_curso_persona, name='add-curso-persona'),
	url(r'^persona/(?P<uuid>[^/]+)/delete/(?P<pk_curso>[^/]+)/$', views.delete_curso_persona, name='delete-curso-persona'),
	url(r'^persona/(?P<uuid>[^/]+)/edit/(?P<pk_curso>[^/]+)/$', views.edit_curso_persona, name='edit-curso-persona'),
	# CONVOCATORIA
	url(r'^puesto/(?P<uuid>[^/]+)/add/$', views.add_curso_convocatoria_puesto, name='add-curso-convocatoria-puesto'),
	url(r'^puesto/(?P<uuid>[^/]+)/delete/(?P<pk_curso>[^/]+)/$', views.delete_curso_convocatoria_puesto, name='delete-curso-convocatoria-puesto'),
	url(r'^puesto/(?P<uuid>[^/]+)/edit/(?P<pk_curso>[^/]+)/$', views.edit_curso_convocatoria_puesto, name='edit-curso-convocatoria-puesto')
]

usuarios/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index_personas, name='index-personas'),
	url(r'^add/$', views.add_persona, name='add-persona'),
	url(r'^find_persona/$', views.find_persona, name='find-persona'),
	url(r'^(?P<uuid>[^/]+)/editar/$', views.edit_persona, name='edit-persona'),
	url(r'^(?P<uuid>[^/]+)/postulaciones/$', views.persona_postulaciones, name='postulaciones-persona'),
	# AUTOCOMPLETE
    url(r'^persona-autocomplete/$', views.PersonaAutocomplete.as_view(), name='persona-autocomplete'),
    url(r'^centro-estudio-autocomplete/$', views.CentroEstudioAutocomplete.as_view(), name='centro-estudio-autocomplete'),
    url(r'^nombre-curso-autocomplete/$', views.NombreCursoAutocomplete.as_view(), name='nombre-curso-autocomplete'),
    url(r'^carreras-autocomplete/$', views.CarrerasAutocomplete.as_view(), name='carreras-autocomplete'),
    url(r'^empresas-autocomplete/$', views.EmpresasAutocomplete.as_view(), name='empresas-autocomplete'),
    url(r'^especialidades-autocomplete/$', views.EspecialidadesAutocomplete.as_view(), name='especialidades-autocomplete'),
    url(r'^sub-especialidades-autocomplete/$', views.SubEspecialidadesAutocomplete.as_view(), name='sub-especialidades-autocomplete'),
	# DOCUMENTOS
	url(r'^(?P<uuid>[^/]+)/documentos/add/$', views.add_documentos_persona, name='add-documento-persona'),
	url(r'^(?P<uuid>[^/]+)/documentos/delete/(?P<pk_documento>[^/]+)/$', views.delete_documentos_persona, name='delete-documento-persona'),
	url(r'^(?P<uuid>[^/]+)/documentos/edit/(?P<pk_documento>[^/]+)/$', views.edit_documentos_persona, name='edit-documento-persona'),
	# PDF
	url(r'^(?P<uuid>[^/]+)/pdf/$', views.PdfCurriculum, name='pdf-persona'),
	url(r'^bloquear/add/$', views.add_bloquear_persona),
	# EXCEL
	# url(r'^excel/$', views.ExcelInformacionPersonas),
	# url(r'^(?P<uuid>[^/]+)/documentos/$', views.add_persona_documentos, name='add-persona-documentos'),
	# API
	url(r'^api/(?P<uuid>[^/]+)/info_laboral/$', views.PersonaInformacionLaboralList.as_view())
]

usuarios/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import uuid

from django.db import models
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save, pre_delete, pre_save
from django.dispatch import receiver
# models
from maestros.models import *
from contratistas.models import *
# Create your models here.
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from maestros.helpers import get_file_path

class Role(models.Model):
	PROYECTO = 1
	CONTRATISTA_PRINCIPAL = 2
	CONTRATISTA = 3
	SUB_CONTRATISTA = 4
	POSTULANTE = 5
	ROLE_CHOICES = (
		(PROYECTO, 'Proyecto'),
		(CONTRATISTA_PRINCIPAL, 'Contratista Principal'),
		(CONTRATISTA, 'Contratista'),
		(SUB_CONTRATISTA, 'Sub Contratista'),
		(POSTULANTE, 'Postulante'),
	)

	user = models.OneToOneField(User, on_delete=models.CASCADE)
	rol = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, null=False, blank=False)

class UserAsociacion(models.Model):
	user = models.ForeignKey(User)
	proyecto = models.ForeignKey(Proyecto, null=True, blank=True)
	contratista_principal = models.ForeignKey(ContratistaPrincipal, null=True, blank=True)
	contratista = models.ForeignKey(Contratista, null=True, blank=True)
	sub_contratista = models.ForeignKey(SubContratista, null=True, blank=True)

	def clean(self):
		if not hasattr(self.user, 'role'):
			raise ValidationError({'user' : _('El usuario no tiene un rol asociado.')})
		else:
			if self.user.role.rol == Role.SUB_CONTRATISTA and self.sub_contratista is None:
				raise ValidationError({'sub_contratista' : _('Asignale una sub_contratista')})
			elif self.user.role.rol == Role.CONTRATISTA and self.contratista is None:
				raise ValidationError({'sub_contratista' : _('Asignale una contratista')})

	class Meta:
		verbose_name = "Asociacion de usuario"
		verbose_name_plural = "Asociacion de usuario"
		unique_together = ('user','proyecto','contratista_principal','contratista','sub_contratista')

class Persona(models.Model):
	ESTADO_CIVIL_SOLTERO = 0
	ESTADO_CIVIL_CASADO = 1
	GENERO_MASCULINO = 0
	GENERO_FEMENINO = 1
	MANO_OBRA_NO_CALIFICADO = 0
	MANO_OBRA_CALIFICADO = 1
	MESES = 0
	ANNIOS = 1

	CHOICES_ESTADOS_CIVIL = ((ESTADO_CIVIL_SOLTERO, 'SOLTERO'), (ESTADO_CIVIL_CASADO, 'CASADO'))
	CHOICES_GENEROS = ((GENERO_MASCULINO, 'MASCULINO'), (GENERO_FEMENINO, 'FEMENINO'))
	CHOICES_MANO_OBRA = ((MANO_OBRA_NO_CALIFICADO, 'NO CALIFICADO'), (MANO_OBRA_CALIFICADO, 'CALIFICADO'))
	CHOICES_TIPO_TIEMPO_RESIDENCIA = ((MESES, 'MESES'), (ANNIOS, u'AÑOS'))

	user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
	user_add = models.ForeignKey(User, null=True, blank=True, related_name='user_add' )
	uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	email = models.EmailField(max_length=200, null=True, blank=True)
	nombres = models.CharField(max_length=255, null=True, blank=True)
	apellidos = models.CharField(max_length=255, null=True, blank=True)
	fecha_nacimiento = models.DateField(null=True, blank=True)
	departamento_nacimiento = models.ForeignKey(PEQ_MAE_departamentos, null=True, blank=True)
	provincia_nacimiento = models.ForeignKey(PEQ_MAE_provincias, null=True, blank=True)
	distrito_nacimiento = models.ForeignKey(PEQ_MAE_distritos, null=True, blank=True)
	departamento_residencia = models.ForeignKey(PEQ_MAE_departamentos, related_name='departamento_residencia', null=True, blank=True)
	provincia_residencia = models.ForeignKey(PEQ_MAE_provincias, related_name='provincia_residencia', null=True, blank=True)
	distrito_residencia = models.ForeignKey(PEQ_MAE_distritos, related_name='distrito_residencia', null=True, blank=True)
	direccion = models.CharField(max_length=255, null=True, blank=True)
	tiempo_residencia = models.PositiveIntegerField(null=True, blank=True, default=0)
	tipo_tiempo_residencia = models.SmallIntegerField(choices=CHOICES_TIPO_TIEMPO_RESIDENCIA, null=True, blank=True, default=0)
	nacionalidad = models.CharField(max_length=255, null=True, blank=True)
	estado_civil = models.SmallIntegerField(choices=CHOICES_ESTADOS_CIVIL, null=False, blank=True, default=0)
	genero = models.SmallIntegerField(choices=CHOICES_GENEROS, null=False, blank=True, default=0)
	mano_obra = models.SmallIntegerField(choices=CHOICES_MANO_OBRA, null=False, blank=True, default=0)
	tipo_documento = models.ForeignKey(PEQ_MAE_tipos_documento, null=True, blank= True)
	numero_documento = models.CharField(max_length=20, null=False, blank=False, unique=True)
	numero_licencia_conducir = models.CharField(max_length=255, null=True, blank=True)
	telefono_fijo = models.CharField(max_length=255, null=True, blank=True)
	celular = models.CharField(max_length=255, null=True, blank=True)
	celular_dos = models.CharField(max_length=255, null=True, blank=True)
	discapacitado = models.BooleanField(default=False)
	verificado = models.BooleanField(default=False)
	declaro = models.BooleanField(default=False)
	imagen = models.FileField(upload_to='personas/', null=True, blank=True)
	tipo_discapacidad = models.ForeignKey(PEQ_MAE_tipos_discapacidad, null=True, blank=True)
	ingles = models.ForeignKey(PEQ_MAE_ingles, null=True, blank=True)
	fecha_creacion = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = "Persona"
		verbose_name_plural = "Personas"
		permissions = (
			("read_persona", "Puede ver personas"),
			("verificar_persona", "Puede verificar personas"),
		)

	def __unicode__(self):
		return '%s' % self.nombres +' '+ self.apellidos

	def delete(self, *args, **kwargs):
		self.user.delete()
		return super(self.__class__, self).delete(*args, **kwargs)

class InformacionEducativa(models.Model):
	persona = models.ForeignKey(Persona)
	centro_estudio = models.ForeignKey(PEQ_MAE_centros_estudio, null=False, blank=False)
	nombre = models.CharField(max_length=255, null=True, blank=True)
	grado = models.ForeignKey(PEQ_MAE_grado, null=False, blank= False)
	estado_grado = models.ForeignKey(PEQ_MAE_estado_grado, null=False, blank=False)
	familia_carrera = models.ForeignKey(PEQ_MAE_familia_carreras, null=True, blank= True)
	carrera = models.ForeignKey(PEQ_MAE_carreras, null=True, blank= True)
	fecha_inicio = models.DateField(null=False, blank=False)
	fecha_fin = models.DateField(null=True, blank=True)
	hasta_actualidad = models.BooleanField(default=False)
	fecha_creacion = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = "Información educativa"
		verbose_name_plural = "Información educativa"

	def __unicode__(self):
		return '%s' % self.nombre

class InformacionLaboral(models.Model):
	persona = models.ForeignKey(Persona)
	empresa = models.ForeignKey(PEQ_MAE_empresas, null=True, blank=True)
	nombre = models.CharField(max_length=255, null=True, blank=True)
	familia_puesto = models.ForeignKey(PEQ_MAE_familia_puesto, null=False, blank= False)
	especialidad = models.ForeignKey(PEQ_MAE_familia, null=False, blank= False)
	sub_especialidad = models.ForeignKey(PEQ_MAE_sub_especialidad, null=True, blank= True)
	rango = models.ForeignKey(PEQ_MAE_rangos, null=True, blank= True)
	fecha_inicio = models.DateField(null=False, blank=False)
	fecha_fin = models.DateField(null=True, blank=True)
	hasta_actualidad = models.BooleanField(default=False)
	fecha_creacion = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = "Información laboral"
		verbose_name_plural = "Información laboral"

	def __unicode__(self):
		return '%s' % self.persona

# documento = models.FileField(upload_to=get_path_for_persona_documento)
# def get_path_for_persona_documento(instance, filename):
# 	return get_file_path('documentos/', filename)

class DocumentosPersonal(models.Model):
	persona = models.ForeignKey(Persona)
	tipo = models.ForeignKey(PEQ_MAE_tipos_documento_personales, null=False, blank=False)
	nombre = models.CharField(max_length=255, null=True, blank=True)
	documento = models.FileField(upload_to=get_file_path)

	class Meta:
		verbose_name = "Documento personal"
		verbose_name_plural = "Documentos personales"
		unique_together = ('persona','tipo')

	def __unicode__(self):
		return '%s' % self.nombre

class CursosPostulantes(models.Model):
	persona = models.ForeignKey(Persona)
	tipo = models.ForeignKey(PEQ_MAE_tipo_cursos, null=False, blank=False)
	nombre = models.ForeignKey(PEQ_MAE_cursos, null=False, blank=False)
	descripcion = models.CharField(max_length=250, null=True, blank=True)
	fecha_inicio = models.DateField(null=False, blank=False)
	fecha_fin = models.DateField(null=True, blank=True)
	hasta_actualidad = models.BooleanField(default=False)
	fecha_creacion = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = 'Cursos del postulante'

class Bloqueados(models.Model):
	uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	numero_documento = models.CharField(max_length=255, null=False, blank=False)
	nombres = models.CharField(max_length=255, null=True, blank=True)
	apellidos = models.CharField(max_length=255, null=True, blank=True)
	direccion = models.CharField(max_length=255, null=True, blank=True)
	celular = models.CharField(max_length=255, null=True, blank=True)
	fecha_creacion = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = "Bloqueados"
		verbose_name_plural = "Bloqueados"

	def __unicode__(self):
		return '%s' % self.numero_documento

usuarios/templates/personas/index_personas.html
{% extends 'base.html' %}
{% block content-header %}{% endblock %}
{% block content-body %}
	<div class="row">
		<form action="" method="GET" class="form-horizontal" >
			<div class="form-group is-empty m-t-5">
				<label for="search" class="col-sm-2 control-label">Buscar</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" id="search" name="search" placeholder="Buscar por numero de documento, nombres o apellidos">
				</div>
				<div class="col-sm-4">
					<button type="submit" class="btn btn-info btn-round m-t-0">buscar</button>
				</div>
			</div>
		</form>
	</div>
	<div class="row">
		{% if personas %}
			<div class="panel-group expansion" id="popout" role="tablist" aria-multiselectable="true">
				{% for persona in personas %}
					<div class="panel panel-default">
						<div class="panel-heading" role="tab" id="heading{{persona.uuid}}">
							<h4 class="panel-title">
								<a {% if not forloop.first %} class="collapsed" {% endif %} role="button" data-toggle="collapse" data-parent="#popout" href="#popout{{persona.uuid}}" aria-expanded="true" aria-controls="popout{{persona.uuid}}">{{persona.nombres}} {{persona.apellidos}}</a>
							</h4>
						</div>
						<div id="popout{{persona.uuid}}" class="panel-collapse collapse {% if forloop.first %} in {% endif %}" role="tabpanel" aria-labelledby="popout{{persona.uuid}}">
							<div class="panel-body">
								{% include "personas/informacion_persona.html" with persona=persona %}
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		{% else %}
			<h1>No hay registros de personas.</h1>
		{% endif %}
	</div>
{% endblock %}

usuarios/templates/personas/informacion_persona.html
<div class="row">
	<div class="col-sm-2">
		<div class="btn-group">
			<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Acciones <span class="caret"></span>
			</button>
			<ul class="dropdown-menu">
				{% if perms.usuarios.change_persona %}
					<li><a href="/personas/{{persona.uuid}}/editar/" ><i class="zmdi zmdi-edit"></i> EDITAR</a></li>
				{% endif %}
				<li><a target="_blank" href="/personas/{{persona.uuid}}/pdf/" ><i class="zmdi zmdi-eye"></i> VER PDF</a></li>
				<li><a target="_blank" href="/personas/{{persona.uuid}}/postulaciones/" ><i class="zmdi zmdi-assignment-check"></i> POSTULACIONES</a></li>
				<li><a target="_blank" href="/educativo/persona/{{persona.uuid}}/add/" ><i class="zmdi zmdi-plus-circle"></i> EDUCACIÓN</a></li>
				<li><a target="_blank" href="/laboral/persona/{{persona.uuid}}/add/" ><i class="zmdi zmdi-plus-circle"></i> LABORAL</a></li>
				<li><a target="_blank" href="/cursos/persona/{{persona.uuid}}/add/" ><i class="zmdi zmdi-plus-circle"></i> ESTUDIOS COMPLEMENTARIOS</a></li>
				<li><a target="_blank" href="/persona/{{persona.uuid}}/documentos/add/" ><i class="zmdi zmdi-plus-circle"></i> DOCUMENTOS</a></li>
			</ul>
		</div>
	</div>
	{% if perms.usuarios.verificar_persona %}
		<div class="col-sm-2">
			{% if persona.verificado %}
				<h3 class="text-success text-uppercase" ><strong><i class="zmdi zmdi-check-circle"></i> verificado</strong></h3>
			{% else %}
				<h3 class="text-danger text-uppercase" ><strong><i class="zmdi zmdi-block"></i> no verificado</strong></h3>
			{% endif %}
		</div>
	{% endif %}
</div>
<div class="row">
	<div class="col-sm-6">
		<div class="row">
			<div class="col-sm-4"><strong class="text-uppercase" >Tipo Doc.:</strong></div>
			<div class="col-sm-8">{{persona.tipo_documento.descripcion|default:''}}</div>
		</div>
		<div class="row">
			<div class="col-sm-4"><strong class="text-uppercase" >Número Doc.</strong></div>
			<div class="col-sm-8">{{persona.numero_documento|default:''}}</div>
		</div>
		<div class="row">
			<div class="col-sm-4"><strong class="text-uppercase" >email:</strong></div>
			<div class="col-sm-8">{{persona.email|default:''}}</div>
		</div>
		<div class="row">
			<div class="col-sm-4"><strong class="text-uppercase" >fecha nac.:</strong></div>
			<div class="col-sm-8">{% if persona.fecha_nacimiento %} {{persona.fecha_nacimiento|date:'d'}} de {{persona.fecha_nacimiento|date:'F Y'}} {% endif %}</div>
		</div>
		<div class="row">
			<div class="col-sm-4"><strong class="text-uppercase" >celular:</strong></div>
			<div class="col-sm-8">{{persona.celular}} - {{persona.celular_dos|default:''}}</div>
		</div>
		<div class="row">
			<div class="col-sm-4"><strong class="text-uppercase" >telefono:</strong></div>
			<div class="col-sm-8">{{persona.telefono_fijo|default:''}}</div>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="row">
			<div class="col-sm-4"><strong class="text-uppercase" >nacionalidad:</strong></div>
			<div class="col-sm-8">{{persona.nacionalidad|default:''}}</div>
		</div>
		<div class="row">
			<div class="col-sm-4"><strong class="text-uppercase" >dirección:</strong></div>
			<div class="col-sm-8">{{persona.direccion|default:''}}</div>
		</div>
		<div class="row">
			<div class="col-sm-4"><strong class="text-uppercase" >Nacimiento:</strong></div>
			<div class="col-sm-8">{{persona.distrito_nacimiento.descripcion|default:''}} {{persona.provincia_nacimiento.descripcion|default:''}} {{persona.departamento_nacimiento.descripcion|default:''}}</div>
		</div>
		<div class="row">
			<div class="col-sm-4"><strong class="text-uppercase" >residencia:</strong></div>
			<div class="col-sm-8">{{persona.distrito_residencia.descripcion|default:''}} {{persona.provincia_residencia.descripcion|default:''}} {{persona.departamento_residencia.descripcion|default:''}}</div>
		</div>
		<div class="row">
			<div class="col-sm-4"><strong class="text-uppercase" >Discapacidad:</strong></div>
			<div class="col-sm-8">
				{% if postulante_convocatoria.persona.discapacitado %}
					SI
					{% if postulante_convocatoria.persona.tipo_discapacidad %} 
						, {{persona.tipo_discapacidad.descripcion}} 
					{% else %} 
						S/D 
					{% endif %}
				{% else %}
					NO
				{% endif %}
			</div>
		</div>
		<div class="row">
			<div class="col-sm-4"><strong class="text-uppercase" >nº licencia:</strong></div>
			<div class="col-sm-8">{{persona.numero_licencia_conducir|default:''}}</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-6">
		<div class="col-sm-12">
			<h2 class="alert alert-info" >Académico</h2>
		</div>
		<div class="list-group">
			{% for educacion in persona.informacioneducativa_set.all|dictsort:"fecha_inicio" %}
				<li class="list-group-item">
					<div class="col-sm-12">
						<span class="pull-left"><span class="img-circle max-w-40 m-r-10 " ><i class="zmdi zmdi-assignment"></i></span></span>
						<div class="list-group-item-body">
							<div class="list-group-item-heading">
								{% if educacion.centro_estudio %} {{educacion.centro_estudio.descripcion}} {% else %} {{educacion.nombre}} {% endif %}
							</div>
							<div class="list-group-item-text">
								<div>{{educacion.grado.descripcion}} {{educacion.familia_grado.descripcion}}</div>
								<div>{% if educacion.hasta_actualidad %} {{educacion.fecha_inicio|timesince:educacion.fecha_fin}} {% else %} {{educacion.fecha_inicio|timesince}} {% endif %} </div>
							</div>
						</div>
					</div>
				</li>
			{% endfor %}
		</div>
	</div>
	<div class="col-sm-6">
		<div class="col-sm-12">
			<h2 class="alert alert-info" >Experiencia</h2>
		</div>
		<div class="list-group">
			{% for experiencia in persona.informacionlaboral_set.all|dictsort:"fecha_inicio" %}
				<li class="list-group-item">
					<div class="col-sm-12">
						<span class="pull-left"><span class="img-circle max-w-40 m-r-10 " ><i class="zmdi zmdi-assignment"></i></span></span>
						<div class="list-group-item-body">
							<div class="list-group-item-heading">
								{{experiencia.empresa.descripcion}}
							</div>
							<div class="list-group-item-text">
								<div>{{experiencia.puesto.descripcion}} / {{experiencia.familia_puesto.descripcion}}</div>
								<div>{{experiencia.fecha_inicio|timesince:experiencia.fecha_fin}}</div>
							</div>
						</div>
					</div>
				</li>
			{% endfor %}
		</div>
	</div>
</div>

usuarios/templates/personas/table_informacion_persona.html
<div class="table-responsive">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>#</th>
				<th>Nombres</th>
				<th>Apellidos</th>
				<th>Nº Documento</th>
				<th>Email</th>
				<th>Género</th>
				<th>Estado</th>
				<th>Celular</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{% for estado in registros %}
				<tr>
					<th scope="row">{{forloop.counter}}</th>
					<td>{{estado.postulacion.persona.nombres}}</td>
					<td>{{estado.postulacion.persona.apellidos}}</td>
					<td>{{estado.postulacion.persona.numero_documento}}</td>
					<td>{{estado.postulacion.persona.email}}</td>
					<td>{{estado.postulacion.persona.get_genero_display}}</td>
					<td>{{estado.postulacion.persona.get_estado_civil_display}}</td>
					<td>{{estado.postulacion.persona.celular|default:''}} {{estado.postulacion.persona.celular_dos|default:''}}</td>
					<td>
						<button type="button" class="btn btn-info btn-sm btn-round btn-view-detail" data-persona="{{estado.postulacion.persona.uuid}}" data-toggle="modal" data-target="#modal__view_detail" >
							<span data-toggle="tooltip" data-placement="top" title="ver detalle" ><i class="zmdi zmdi-eye"></i></span>
						</button>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

usuarios/templates/personas/title_persona.html
<div class="col-sm-9">
	<h2> <strong>persona:</strong> {{persona.nombres|upper}} {{persona.apellidos|upper}} <strong>nº documento:</strong> {{persona.numero_documento}} </h2>
</div>
<div class="col-sm-3">
	<div class="dropdown">
		<button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
			acciones
			<span class="caret"></span>
		</button>
		<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
			{% if perms.usuarios.change_persona %}
				<li>
					<a href="/personas/{{persona.uuid}}/editar/" class="text-uppercase" ><i class="zmdi zmdi-edit"></i> editar</a>
				</li>
			{% endif %}
			<li>
				<a href="/personas/{{persona.uuid}}/pdf/" class="text-uppercase" ><i class="zmdi zmdi-eye"></i> ver pdf</a>
			</li>
			<li><a href="/educativo/persona/{{persona.uuid}}/add/" ><i class="zmdi zmdi-plus-circle"></i> EDUCACIÓN</a></li>
			<li><a href="/laboral/persona/{{persona.uuid}}/add/" ><i class="zmdi zmdi-plus-circle"></i> LABORAL</a></li>
			<li><a href="/cursos/persona/{{persona.uuid}}/add/" ><i class="zmdi zmdi-plus-circle"></i> ESTUDIOS COMPLEMENTARIOS</a></li>
			<li><a href="/personas/{{persona.uuid}}/documentos/add/" ><i class="zmdi zmdi-plus-circle"></i> DOCUMENTOS</a></li>
		</ul>
	</div>
</div>