PetroReclutamiento/urls.py
from django.conf.urls import url, include, handler403, handler404, handler500
from django.contrib import admin
# STATICFILES
from django.conf import settings
from django.conf.urls.static import static
from usuarios import views as users_views
from maestros import views as maestros_views
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^password_change/$', auth_views.password_change, name='password_change'),
    url(r'^password_change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^$', RedirectView.as_view(pattern_name='login', permanent=False)),
    url(r'^login/', users_views.login_view, name='login'),
    url(r'^logout/', users_views.logout_view),
    url(r'^admin/', admin.site.urls),
    url(r'^convocatorias/', include('convocatorias.urls')),
    url(r'^publico/', include('publico.urls')),
    url(r'^personas/', include('usuarios.urls')),
    url(r'^atenciones/', include('atenciones.urls')),
    url(r'^educativo/', include('educativo.urls')),
    url(r'^laboral/', include('laboral.urls')),
    url(r'^cursos/', include('cursos.urls')),
    url(r'^api/maestros/', include('maestros.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
    # url(r'^.*$', RedirectView.as_view(pattern_name='login', permanent=False))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler403 = maestros_views.handler403
handler404 = maestros_views.handler404
handler500 = maestros_views.handler500

convocatorias/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index_convocatoria, name='index-convocatoria'),
	url(r'^add/$', views.add_convocatoria, name='add-convocatoria'),
	url(r'^(?P<uuid>[^/]+)/editar/$', views.edit_convocatoria, name='edit-convocatoria'),
	url(r'^(?P<uuid>[^/]+)/eliminar/$', views.delete_convocatoria, name='delete-convocatoria'),
	url(r'^(?P<uuid>[^/]+)/puestos/$', views.add_convocatoria_puestos, name='add-convocatoria-puestos'),
	url(r'^(?P<uuid>[^/]+)/codigo/$', views.get_codigo_convocatoria, name='get-codigo-convocatoria'),
	url(r'^puestos/(?P<uuid>[^/]+)/editar/$', views.edit_convocatoria_puesto, name='edit-convocatoria-puesto'),
	url(r'^puestos/(?P<uuid>[^/]+)/delete/$', views.delete_convocatoria_puesto, name='delete-convocatoria-puesto'),
	url(r'^puestos/(?P<uuid>[^/]+)/postulantes/$', views.detail_convocatoria, name='detail-convocatoria'),
	url(r'^puestos/(?P<uuid>[^/]+)/postular/(?P<uuid_persona>[^/]+)/$', views.postulacion_convocatoria, name='postulacion-convocatoria'),
	url(r'^puestos/(?P<uuid>[^/]+)/pases_ingreso/$', views.pase_de_ingreso, name='pase-de-ingreso'),
	url(r'^puestos/(?P<uuid>[^/]+)/pases_ingreso/(?P<uuid_criterio>[^/]+)/$', views.pase_de_ingreso_add_persona, name='pase-de-ingreso-add-persona'),
	url(r'^pases_ingreso/(?P<uuid>[^/]+)/$', views.pase_de_ingreso_add_files, name='pase-de-ingreso-add-files'),
	# url(r'^puestos/(?P<uuid>[^/]+)/pases_ingreso/(?P<uuid_persona>[^/]+)/$', views.postulacion_convocatoria, name='postulacion-convocatoria'),
	url(r'^puesto/(?P<uuid>[^/]+)/personas/$', views.convocatoria_puesto_personas, name='convocatoria-puesto-personas'),
	url(r'^puesto/postular/$', views.postular_convocatoria_puesto, name='postular-convocatoria-puesto'),
	url(r'^puestos/(?P<uuid>[^/]+)/preseleccion/$', views.pre_seleccion, name='pre-seleccion'),
	url(r'^puestos/(?P<uuid>[^/]+)/add_preseleccion/$', views.add_pre_seleccion, name='add-pre-seleccion'),
	url(r'^puestos/(?P<uuid>[^/]+)/verificacion/$', views.verificacion, name='verificacion'),
	url(r'^puestos/(?P<uuid>[^/]+)/contactabilidad/$', views.contactabilidad, name='contactabilidad'),
	url(r'^puestos/(?P<uuid>[^/]+)/sesion_preseleccion/$', views.sesion_preseleccion, name='sesion_preseleccion'),
	url(r'^puestos/(?P<uuid>[^/]+)/aprobados/$', views.aprobados, name='aprobados'),
	url(r'^puestos/(?P<uuid>[^/]+)/tramite_documentario/$', views.tramite_documentario),
	url(r'^puestos/(?P<uuid>[^/]+)/criterios_busqueda/$', views.CriteriosBusqueda, name='criterios-busqueda'),
	url(r'^puestos/(?P<uuid>[^/]+)/criterios_busqueda_avanzada/$', views.criterios_avanzados),
	url(r'^puestos/(?P<uuid>[^/]+)/add_porcentaje_cumplimiento/$', views.add_porcentaje_cumplimiento),
	url(r'^puestos/(?P<uuid>[^/]+)/add_porcentaje_cumplimiento_criterio/$', views.add_porcentaje_cumplimiento_criterio),
	
	url(r'^estado_postulacion/(?P<pk>[^/]+)/visitado/$', views.postulante_visitado, name='postulante-llamado'),
	url(r'^estado_postulacion/(?P<pk>[^/]+)/verificado/$', views.postulante_verificado, name='confirmar-postulante'),
	url(r'^estado_postulacion/(?P<pk>[^/]+)/llamado/$', views.postulante_llamado, name='postulante-llamado'),
	url(r'^estado_postulacion/(?P<pk>[^/]+)/confirmado/$', views.confirmar_postulante, name='confirmar-postulante'),
	url(r'^estado_postulacion/(?P<pk>[^/]+)/entrevista/$', views.aprobado_entrevista, name='aprobado-entrevista'),
	url(r'^estado_postulacion/(?P<pk>[^/]+)/apto/$', views.aprobado_apto, name='aprobado_apto'),
	url(r'^estado_postulacion/(?P<pk>[^/]+)/observaciones/$', views.add_observaciones_postulacion, name='add-observaciones-postulacion'),
	url(r'^estado_postulacion/(?P<pk>[^/]+)/documentos/$', views.add_documentos_postulacion),

	url(r'^puestos/(?P<uuid>[^/]+)/preseleccionados/(?P<tipo_ingreso>[^/]+)/(?P<orden>[^/]+)/$', views.list_preseleccionados, name='list_preseleccionados'),
	url(r'^puestos/(?P<uuid>[^/]+)/aprobar_preseleccion/$', views.aprobar_pre_seleccion, name='aprobar-pre-seleccion'),
	url(r'^puestos/(?P<uuid>[^/]+)/contratar_aprobados/$', views.contratar_aprobados),
	# CRITERIOS AVANZADOS
	url(r'^add_plantilla_criterio_avanzado/$', views.add_plantilla_criterio_avanzado),
	url(r'^plantilla/(?P<uuid>[^/]+)/add_criterio/$', views.add_criterio_to_plantilla),
	url(r'^puestos/(?P<uuid>[^/]+)/add_extras_criterio_avanzado/$', views.add_extras_criterio_avanzado),

	url(r'^(?P<uuid>[^/]+)/autorizar/$', views.autorizar_convocatoria, name='autorizar-convocatoria'),
	url(r'^(?P<uuid>[^/]+)/iniciar/$', views.iniciar_convocatoria, name='iniciar-convocatoria'),
	url(r'^puestos/(?P<uuid>[^/]+)/preseleccion_manual/$', views.pre_seleccion_manual, name='pre-seleccion-manual'),
	url(r'^preseleccion/add_tags/$', views.add_pre_seleccion_tags, name='add-pre-seleccion-tags'),

	url(r'^search/$', views.search_name_puesto),	
	# PDFS
	url(r'^(?P<uuid>[^/]+)/pdf/$', views.PdfConvocatorias),	
	url(r'^puestos/(?P<uuid>[^/]+)/pdf/preseleccionados/$', views.PdfPreseleccionados),	
	url(r'^puestos/(?P<uuid>[^/]+)/pdf/seleccionados/$', views.PdfSeleccionados),	
	url(r'^puesto/(?P<uuid>[^/]+)/pdf/verificacion_domiciliaria/$', views.PdfVerificacionDomiciliaria),	
	url(r'^puesto/(?P<uuid>[^/]+)/pdf/pases_de_ingreso/$', views.PdfPasesDeIngreso),	
	# DOCUMENTOS
	url(r'^puesto/(?P<uuid>[^/]+)/documentos/add/$', views.add_documentos_convocatoria_puesto, name='add-documento-convocatoria-puesto'),
	url(r'^puesto/(?P<uuid>[^/]+)/documentos/delete/(?P<pk_documento>[^/]+)/$', views.delete_documentos_convocatoria_puesto, name='delete-documento-convocatoria-puesto'),
	url(r'^puesto/(?P<uuid>[^/]+)/documentos/edit/(?P<pk_documento>[^/]+)/$', views.edit_documentos_convocatoria_puesto, name='edit-documento-convocatoria-puesto'),
	# REQUISITOS
	url(r'^puesto/(?P<uuid>[^/]+)/requisito/add/$', views.add_requisitos_convocatoria_puesto, name='add-requisito-convocatoria-puesto'),
	url(r'^puesto/(?P<uuid>[^/]+)/requisito/delete/(?P<uuid_requisito>[^/]+)/$', views.delete_requisitos_convocatoria_puesto, name='delete-requisito-convocatoria-puesto'),
	url(r'^puesto/(?P<uuid>[^/]+)/requisito/edit/(?P<uuid_requisito>[^/]+)/$', views.edit_requisitos_convocatoria_puesto, name='edit-requisito-convocatoria-puesto'),
]

cursos/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	# PERSONA
	url(r'^persona/(?P<uuid>[^/]+)/add/$', views.add_curso_persona, name='add-curso-persona'),
	url(r'^persona/(?P<uuid>[^/]+)/delete/(?P<pk_curso>[^/]+)/$', views.delete_curso_persona, name='delete-curso-persona'),
	url(r'^persona/(?P<uuid>[^/]+)/edit/(?P<pk_curso>[^/]+)/$', views.edit_curso_persona, name='edit-curso-persona'),
	# CONVOCATORIA
	url(r'^puesto/(?P<uuid>[^/]+)/add/$', views.add_curso_convocatoria_puesto, name='add-curso-convocatoria-puesto'),
	url(r'^puesto/(?P<uuid>[^/]+)/delete/(?P<pk_curso>[^/]+)/$', views.delete_curso_convocatoria_puesto, name='delete-curso-convocatoria-puesto'),
	url(r'^puesto/(?P<uuid>[^/]+)/edit/(?P<pk_curso>[^/]+)/$', views.edit_curso_convocatoria_puesto, name='edit-curso-convocatoria-puesto')
]

publico/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index_public, name='index-publico'),
	url(r'^login/$', views.login_public),
	url(r'^registrarse/$', views.register_public),
	url(r'^perfil/$', views.profile_public),
	url(r'^editar/perfil/$', views.edit_profile_public),
	url(r'^postulaciones/$', views.postulaciones_public),
	url(r'^convocatorias/$', views.convocatorias_public),
	url(r'^preseleccionados/$', views.preseleccionados_public),
	url(r'^seleccionados/$', views.seleccionados_public),
	url(r'^convocatoria/puesto/(?P<uuid>[^/]+)/$', views.convocatoria_detail),
	url(r'^convocatoria/puesto/(?P<uuid>[^/]+)/(?P<fecha>[^/]+)/preseleccionados/$', views.convocatoria_puesto_preseleccionados_detail),
	url(r'^convocatoria/puesto/(?P<uuid>[^/]+)/(?P<fecha>[^/]+)/seleccionados/$', views.convocatoria_puesto_seleccionados_detail),
	url(r'^postular/puesto/(?P<uuid>[^/]+)/$', views.publico_postular_convocatoria),
]

atenciones/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from maestros.models import PEQ_MAE_tipo_atencion, PEQ_MAE_capacitaciones
from usuarios.models import Persona
from django.contrib.auth.models import User

import uuid

class Atenciones(models.Model):
	uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	user = models.ForeignKey(User, null=True, blank=True)
	persona = models.ForeignKey(Persona, null=True, blank=True)
	tipo = models.ForeignKey(PEQ_MAE_tipo_atencion, null=False, blank=False)
	capacitacion = models.ForeignKey(PEQ_MAE_capacitaciones, null=True, blank=True)
	observaciones = models.CharField(max_length=1000, null=True, blank=True)
	fecha = models.DateField(null=False, blank=False)
	hora_inicio = models.TimeField(null=False, blank=False)
	hora_fin = models.TimeField(null=True, blank=True)
	fecha_finalizacion = models.DateField(null=True, blank=True)
	finalizada = models.BooleanField(default=False)
	fecha_creacion = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = "Atención"
		verbose_name_plural = "Atenciones"

	def __unicode__(self):
		return '{0} {1}'.format(self.persona.dni, self.fecha)

publico/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

convocatorias/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import Convocatoria, ConvocatoriaPuesto,PEQ_INT_convocatoria_academico, PEQ_INT_convocatoria_experiencia, PEQ_INT_convocatoria_cursos, PEQ_INT_convocatoria_documentos
from contratistas.models import Contratista
from maestros.models import PEQ_MAE_requisitos
# AUTOCOMPLETE
from dal import autocomplete

class ConvocatoriaForm(forms.ModelForm):
	error_css_class = 'error'
	required_css_class = 'required'

	nombre = forms.CharField(label='Nombre', widget=forms.TextInput(attrs={'class' : 'form-control'}))
	codigo = forms.CharField(label=u'Código', widget=forms.TextInput(attrs={'class' : 'form-control', 'readonly':'true'}))
	# remuneracion = forms.IntegerField(label=u'Remuneración', error_messages={'invalid': 'Ingresar solo numeros.'},widget=forms.TextInput(attrs={'class' : 'form-control'}))
	fecha_inicio = forms.DateField(label='Inicio', widget=forms.TextInput(attrs={'class' : 'form-control datepicker', 'id':'fecha_inicio'}))
	fecha_fin = forms.DateField(label='Fin', widget=forms.TextInput(attrs={'class' : 'form-control datepicker', 'id':'fecha_fin'}))
	condiciones_adicionales = forms.CharField(label='Condiciones Adicionales', widget=forms.Textarea(attrs={'class' : 'form-control', 'rows':'5'}))
	# requisitos_funciones = forms.CharField(label='Requisitos', widget=forms.Textarea(attrs={'class' : 'form-control', 'rows':'5'}))

	class Meta:
		model = Convocatoria
		fields = ('nombre','codigo','remuneracion','contratista','lugar','fecha_inicio','fecha_fin','condiciones_adicionales')
		widgets = {
			'contratista': forms.Select(attrs={'class': 'normal__select'}),
			'lugar': forms.Select(attrs={'class': 'normal__select'}),
			'remuneracion': forms.Select(attrs={'class': 'normal__select'}),
		}

class ConvocatoriaPuestoForm(forms.ModelForm):
	cantidad_vacantes = forms.IntegerField(label='Vacantes', error_messages={'invalid': 'Ingresar solo numeros.'},widget=forms.NumberInput(attrs={'class' : 'form-control'}))
	edad_minima = forms.IntegerField(label='Edad Mín.', error_messages={'invalid': 'Ingresar solo numeros.'},widget=forms.NumberInput(attrs={'class' : 'form-control'}))
	edad_maxima = forms.IntegerField(label='Edad Max.', error_messages={'invalid': 'Ingresar solo numeros.'},widget=forms.NumberInput(attrs={'class' : 'form-control'}))

	class Meta:
		model = ConvocatoriaPuesto
		fields = ('familia_puesto','especialidad','sub_especialidad','rango','cantidad_vacantes','duracion_contrato','edad_minima','edad_maxima')
		widgets = {
			'familia_puesto': forms.Select(attrs={'class': 'normal__select'}),
			'especialidad': autocomplete.ModelSelect2(url='especialidades-autocomplete', forward=['familia_puesto']),
			'sub_especialidad': autocomplete.ModelSelect2(url='sub-especialidades-autocomplete', forward=['especialidad']),
			'rango': forms.Select(attrs={'class': 'normal__select'}),
			'duracion_contrato': forms.Select(attrs={'class': 'normal__select'}),
		}

	def clean(self):
		cleaned_data = super(ConvocatoriaPuestoForm, self).clean()
		edad_minima = int(cleaned_data.get("edad_minima"))
		edad_maxima = int(cleaned_data.get("edad_maxima"))
		# validate edad
		self.add_error('edad_maxima', "Edad Máxima debe ser mayor") if edad_maxima < edad_minima else ''

class ConvocatoriaAcademicoForm(forms.ModelForm):

	class Meta:
		model = PEQ_INT_convocatoria_academico
		fields = ('grado','estado_grado','familia_carrera','carrera','indispensable')
		widgets = {
			'familia_carrera': forms.Select(attrs={'class': 'normal__select'}),
			'carrera': autocomplete.ModelSelect2(url='carreras-autocomplete', forward=['familia_carrera']),
			'grado': forms.Select(attrs={'class': 'normal__select'}),
			'estado_grado': forms.Select(attrs={'class': 'normal__select'})
		}

class ConvocatoriaExperienciaForm(forms.ModelForm):

	class Meta:
		model = PEQ_INT_convocatoria_experiencia
		fields = ('familia_puesto','especialidad','sub_especialidad','rango','experiencia')
		widgets = {
			'familia_puesto': forms.Select(attrs={'class': 'normal__select'}),
			'especialidad': autocomplete.ModelSelect2(url='especialidades-autocomplete', forward=['familia_puesto']),
			'sub_especialidad': autocomplete.ModelSelect2(url='sub-especialidades-autocomplete', forward=['especialidad']),
			'rango': forms.Select(attrs={'class': 'normal__select'}),
			'experiencia': forms.Select(attrs={'class': 'normal__select'})
		}

class ConvocatoriaCursosForm(forms.ModelForm):

	descripcion = forms.CharField(label='Descripción', required=True,widget=forms.Textarea(attrs={'class' : 'form-control', 'rows':'3'}))

	class Meta:
		model = PEQ_INT_convocatoria_cursos
		fields = ('tipo','nombre','descripcion','indispensable')
		widgets = {
			'tipo' : forms.Select(attrs={'class': 'normal__select','required':'required'}),
			'nombre' : autocomplete.ModelSelect2(url='nombre-curso-autocomplete'),
		}

class ConvocatoriaDocumentosForm(forms.ModelForm):

	class Meta:
		model = PEQ_INT_convocatoria_documentos
		fields = ('tipo_documento','detalle_documento','indispensable')
		widgets = {
			'tipo_documento' : forms.Select(attrs={'class': 'normal__select','required':'required'}),
			'detalle_documento' : forms.Select(attrs={'class': 'normal__select','required':'required'}),
		}

class RequisitoConvocatoriaForm(forms.ModelForm):

	descripcion = forms.CharField(label='Descripción', widget=forms.Textarea(attrs={'class' : 'form-control', 'rows':'5'}))

	class Meta:
		model = PEQ_MAE_requisitos
		fields = ('descripcion',)

publico/templates/convocatoria_puesto_detail.html
{% extends 'base_publico.html' %}
{% load static %}
{% block content %}
	<section id="about">
		<div class="container">
			<div id="message_postulacion" class="alert" role="alert"></div>
			{% if not user.persona.verificado and user.is_authenticated %}
				<div class="alert alert-danger" role="alert" >Aún no estas verificado, acércate a recepción para validar tus documentos.</div>
			{% endif %}
			<div class="row">
				<div class="col-sm-1"></div>
				<div class="col-sm-10 text-center"><h3 class="text-info text-uppercase" >{{title}}</h3></div>
				<div class="col-sm-1">
					{% if user.is_authenticated %}
						{% if user.persona.verificado %}
							{% if postulacion %}
								<div><span class="text-success" >Postulado</span></div>
							{% else %}
								<div><button type="button" class="btn btn-success text-uppercase publico_postular_puesto" data-puesto="{{puesto.uuid}}" >postular</button></div>
							{% endif %}
						{% endif %}
					{% endif %}
				</div>
			</div>
			<div class="row">
				<h4 class="text-uppercase" >I. Información general</h4>
			</div>
			<div class="row">
				<div class="col-sm-6 row" style="margin-top: 10px;">
					<div class="col-sm-12"><h6><strong>Convocatoria:</strong></h6></div>
					<div class="col-sm-12">{{puesto.convocatoria.nombre}}</div>
				</div>
				<div class="col-sm-6 row" style="margin-top: 10px;">
					<div class="col-sm-12"><h6><strong>Contratista:</strong></h6></div>
					<div class="col-sm-12">{{puesto.convocatoria.contratista.nombre}}</div>
				</div>
				<div class="col-sm-6 row" style="margin-top: 10px;">
					<div class="col-sm-12"><h6><strong>(Cantidad de vacantes) nombre del puesto:</strong></h6></div>
					<div class="col-sm-12">{{title}}</div>
				</div>
				<div class="col-sm-6 row" style="margin-top: 10px;">
					<div class="col-sm-12"><h6><strong>Inicio / Cierre de postulación:</strong></h6></div>
					<div class="col-sm-12">{% if estado.fecha_inicio %} {{estado.fecha_inicio|date:'d'}} de {{estado.fecha_inicio|date:'F Y'}} {% endif %} {% if estado.fecha_fin %} / {{estado.fecha_fin|date:'d'}} de {{estado.fecha_fin|date:'F Y'}} {% endif %}</div>
				</div>
				<div class="col-sm-6 row" style="margin-top: 10px;">
					<div class="col-sm-12"><h6><strong>Remuneración:</strong></h6></div>
					<div class="col-sm-12">{{puesto.convocatoria.remuneracion.descripcion}}</div>
				</div>
				<div class="col-sm-6 row" style="margin-top: 10px;">
					<div class="col-sm-12"><h6><strong>Duración:</strong></h6></div>
					<div class="col-sm-12">{{puesto.duracion_contrato.descripcion}}</div>
				</div>
				<div class="col-sm-6 row" style="margin-top: 10px;">
					<div class="col-sm-12"><h6><strong>Duración:</strong></h6></div>
					<div class="col-sm-12">{{puesto.duracion_contrato.descripcion}}</div>
				</div>
				<div class="col-sm-6 row" style="margin-top: 10px;">
					<div class="col-sm-12"><h6><strong>Condiciones adicionales:</strong></h6></div>
					<div class="col-sm-12">{{puesto.convocatoria.condiciones_adicionales}}</div>
				</div>
			</div>
			<div class="row" style="margin-top: 15px;" >
				<h4 class="text-uppercase" >II. requisitos</h4>
			</div>
			<!-- FORMACIÓN ACADEMICA -->
			<div class="row">
				<div class="col-sm-12 row text-center text-uppercase" style="margin-top: 10px;"><h6>formación académica</h6></div>
				<ul class="row">
					{% for educativo in puesto.peq_int_convocatoria_academico_set.all %}
						<li class="col-sm-12" >{{educativo.grado.descripcion}} {{educativo.estado_grado.descripcion}} {{educativo.carrera.descripcion}}</li>
					{% endfor %}
				</ul>
			</div>
			<!-- EXPERIENCIA LABORAL -->
			<div class="row">
				<div class="col-sm-12 row text-center text-uppercase" style="margin-top: 10px;"><h6>experiencia laboral</h6></div>
				<ul class="row">
					{% for educativo in puesto.peq_int_convocatoria_experiencia_set.all %}
						{% if educativo.tipo_registro == 0 %}
							<li class="col-sm-12" >{{educativo.rango.descripcion}} {{educativo.sub_especialidad.descripcion}} {{educativo.especialidad.descripcion}} {{educativo.experiencia.tiempo}} {{educativo.experiencia.get_tipo_display}}</li>
						{% endif %}
					{% endfor %}
					{% for requisito in puesto.requisitos.all %}
						<li class="col-sm-12" >{{requisito.descripcion}}</li>
					{% endfor %}
				</ul>
			</div>
			<!-- CURSOS CAPACITACIONES -->
			<div class="row">
				<div class="col-sm-12 row text-center text-uppercase" style="margin-top: 10px;"><h6>cursos / capacitaciones</h6></div>
				<ul class="row">
					{% for curso in puesto.peq_int_convocatoria_cursos_set.all %}
						<li class="col-sm-12" >{{curso.tipo.descripcion}} {{curso.nombre.descripcion}} {{curso.descripcion}}</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</section>	
{% endblock content %}

publico/templates/convocatoria_puesto_preseleccionado_detail.html
{% extends 'base_publico.html' %}
{% load static %}
{% block content %}
	<section id="about">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 text-center"><h3 class="text-info text-uppercase" >{{title}}</h3></div>
				<div class="col-sm-12 text-center"><h5 class="text-info text-lowercase" >{{preseleccionados|length}} hasta el día {% if fecha %} {{fecha|date:'d'}} de {{fecha|date:'F Y'}} {% endif %}</h5></div>
			</div>
			<div class="row">
				<table class="table table-striped">
					<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">Nº Documento</th>
							<th scope="col">Nombre</th>
							<th scope="col">Apellidos</th>
						</tr>
					</thead>
					<tbody>
						{% for preseleccionado in preseleccionados %}
							<tr>
								<th scope="row">{{forloop.counter}}</th>
								<td>{{preseleccionado.postulacion.persona.numero_documento}}</td>
								<td>{{preseleccionado.postulacion.persona.nombres}}</td>
								<td>{{preseleccionado.postulacion.persona.apellidos}}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</section>	
{% endblock content %}

publico/templates/convocatoria_puesto_seleccionado_detail.html
{% extends 'base_publico.html' %}
{% load static %}
{% block content %}
	<section id="about">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 text-center"><h3 class="text-info text-uppercase" >{{title}}</h3></div>
				<div class="col-sm-12 text-center"><h5 class="text-info text-lowercase" >{{seleccionados|length}} hasta el día {% if fecha %} {{fecha|date:'d'}} de {{fecha|date:'F Y'}} {% endif %}</h5></div>
			</div>
			<div class="row">
				<table class="table table-striped">
					<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">Nº Documento</th>
							<th scope="col">Nombre</th>
							<th scope="col">Apellidos</th>
						</tr>
					</thead>
					<tbody>
						{% for seleccionado in seleccionados %}
							<tr>
								<th scope="row">{{forloop.counter}}</th>
								<td>{{seleccionado.postulacion.persona.numero_documento}}</td>
								<td>{{seleccionado.postulacion.persona.nombres}}</td>
								<td>{{seleccionado.postulacion.persona.apellidos}}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</section>	
{% endblock content %}